import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,addDays} from '../src/data.js';
import {taskBase,createDay,scheduleDay,generateTasks,integrateTour,validateShifts,pauses,shiftBounds,manualPlacement,topstockProgress,personMetrics,overlap,remaining} from '../src/engine.js';
import {validateState,saveWorkspace,loadWorkspace,STORAGE_KEY} from '../src/storage.js';
function fixture(){const s=initialState();s.profile={name:'Test',leadId:'p1'};s.departments=[{id:'14',name:'Kitchen'},{id:'17',name:'Home'}];s.team=[{id:'p1',name:'One',role:'Team lead',active:true,departments:[]},{id:'p2',name:'Two',role:'Associate',active:true,departments:[]}];s.aisles=Array.from({length:12},(_,i)=>({id:'a'+i,label:'H'+(i+1),department:i<6?'14':'17',topstock:true,zoneMinutes:20,topMinutes:20}));for(const r of Object.values(s.settings.routines))r.enabled=false;return s;}
const shifts=()=>['p1','p2'].map(personId=>({personId,start:420,end:960,mealStart:660,mealMinutes:60,breaks:[{start:540,minutes:15},{start:840,minutes:15}]}));
const plan=(tasks=[],sf=shifts(),date='2026-09-14')=>({date,shifts:sf,tasks,tour:[],reviewed:false,warnings:[]});
test('backup IDs cannot inject markup and carryover does not reuse yesterday’s actual minutes',()=>{const s=fixture(),d=plan([taskBase({minutes:60,progress:50,actualMinutes:40})]);d.reviewed=true;s.days.push(d);assert.equal(createDay(s,'2026-09-15',shifts()).tasks[0].actualMinutes,undefined);s.team[1].id='bad" onclick="bad';assert.throws(()=>validateState(s));});
function assertSound(day){for(const s of day.shifts){const bounds=shiftBounds(s),all=day.tasks.filter(t=>t.assignedTo===s.personId).flatMap(t=>t.segments);for(const [i,segment] of all.entries()){assert.ok(segment.start>=bounds.start&&segment.end<=bounds.end);assert.ok(!pauses(s).some(p=>overlap(p,segment)));assert.ok(!all.slice(i+1).some(p=>overlap(p,segment)));}}}
test('scheduling splits long work around breaks, balances load, never overlaps',()=>{const s=fixture(),d=scheduleDay(s,plan(Array.from({length:12},(_,i)=>taskBase({title:'Task '+i,minutes:70}))));assertSound(d);assert.equal(d.tasks.filter(t=>!t.assignedTo).length,0);assert.equal(d.tasks.filter(t=>t.assignedTo==='p1').length,6);});
test('capacity overflow remains visible with an explanation',()=>{const s=fixture(),d=scheduleDay(s,plan([taskBase({minutes:960}),taskBase({minutes:30})]));assert.equal(d.tasks.filter(t=>!t.assignedTo).length,1);assert.ok(d.tasks[0].unscheduledReason);assert.ok(d.warnings.length);});
test('overnight shifts, overnight meals and morning windows are respected',()=>{const s=fixture(),sf=[{personId:'p1',start:1320,end:420,mealStart:120,mealMinutes:60,breaks:[{start:0,minutes:15}]}],d=scheduleDay(s,plan([taskBase({minutes:90,window:{start:180,end:300}})],sf));assert.equal(validateShifts(sf),'');assert.equal(d.tasks[0].segments[0].start,1620);assertSound(d);});
test('overlapping or out-of-shift meals are rejected',()=>{const sf=shifts();sf[0].breaks=[{start:680,minutes:15}];assert.match(validateShifts(sf),/overlapping/);sf[0].breaks=[];sf[0].mealStart=950;assert.match(validateShifts(sf),/inside/);});
test('RFID follows each department calendar; non-RFID deep outs run Tuesday',()=>{const s=fixture();s.settings.routines.rfid.enabled=true;s.settings.rfid['14']={enabled:true,days:[1,3]};const mon=generateTasks(s,plan()),tue=generateTasks(s,plan([],shifts(),'2026-09-15'));assert.equal(mon.length,1);assert.equal(mon[0].kind,'rfid');assert.equal(mon[0].department,'14');assert.equal(tue.length,1);assert.equal(tue[0].kind,'outs');assert.equal(tue[0].department,'17');});
test('top stock reaches every eligible aisle by Friday when capacity is available',()=>{const s=fixture();s.settings.routines.topstock.enabled=true;s.aisles[0].topstock=false;for(let i=0;i<5;i++){const d=createDay(s,addDays('2026-09-14',i),shifts());assertSound(d);const counts=d.shifts.map(p=>d.tasks.filter(t=>t.assignedTo===p.personId).length);assert.ok(Math.max(...counts)-Math.min(...counts)<=1);d.tasks.forEach(t=>{t.status='done';t.progress=100;});d.reviewed=true;s.days.push(d);}assert.equal(topstockProgress(s,'2026-09-18').done,11);assert.equal(s.days.flatMap(d=>d.tasks).length,11);});
test('Friday schedules every outstanding top-stock aisle and exposes shortfalls',()=>{const s=fixture();s.settings.routines.topstock.enabled=true;const sf=[{personId:'p1',start:420,end:450,mealStart:420,mealMinutes:0,breaks:[]}],d=createDay(s,'2026-09-18',sf);assert.equal(d.tasks.length,12);assert.equal(d.tasks.filter(t=>!t.assignedTo).length,11);});
test('zoning prioritizes never-zoned aisles before recently completed aisles',()=>{const s=fixture();s.settings.routines.zone.enabled=true;s.settings.zoneWindow={start:900,end:920};s.days=[{...plan([taskBase({kind:'zone',aisleId:'a0',status:'done',progress:100})],shifts(),'2026-09-13'),reviewed:true}];const d=createDay(s,'2026-09-14',shifts());assert.equal(d.tasks.length,2);assert.ok(d.tasks.every(t=>t.aisleId!=='a0'));assertSound(d);});
test('tour zoning replaces automatic aisle work and displaces the next auto zone',()=>{const s=fixture();s.settings.routines.zone.enabled=true;s.settings.zoneWindow={start:900,end:920};const d=createDay(s,'2026-09-14',shifts()),note=taskBase({kind:'zone',aisleId:'a11',department:'17',minutes:20,priority:'high'}),next=integrateTour(s,d,[note]);assert.equal(next.tasks.length,2);assert.equal(next.tasks.filter(t=>t.aisleId==='a11').length,1);assert.ok(next.tasks.find(t=>t.aisleId==='a11').assignedTo);assert.equal(integrateTour(s,next,[note]).tasks.length,next.tasks.length);assertSound(next);});
test('pinned, completed and started work survives replanning',()=>{const s=fixture(),d=scheduleDay(s,plan([taskBase({minutes:30}),taskBase({minutes:30}),taskBase({minutes:30})]));d.tasks[0].locked=true;d.tasks[1].status='in-progress';d.tasks[2].status='done';d.tasks[2].progress=100;const original=structuredClone(d.tasks);const next=integrateTour(s,d,[taskBase({priority:'urgent',minutes:60})]);for(let i=0;i<3;i++)assert.deepEqual(next.tasks[i].segments,original[i].segments);assertSound(next);});
test('day follow-up is required and incomplete work carries remaining estimates once',()=>{const s=fixture(),d=plan([taskBase({minutes:40,progress:25}),taskBase({minutes:30,status:'done',progress:100})]);s.days.push(d);assert.throws(()=>createDay(s,'2026-09-15',shifts()),/follow-up/);d.reviewed=true;const next=createDay(s,'2026-09-15',shifts());assert.equal(next.tasks.length,1);assert.equal(next.tasks[0].minutes,30);assert.equal(next.tasks[0].progress,0);assert.equal(next.tasks[0].source,'carry');s.days.push(next);assert.throws(()=>createDay(s,'2026-09-15',shifts()),/already exists/);});
test('partial modular carryover replaces the full-size modular in new routines',()=>{const s=fixture();s.settings.routines.modular.enabled=true;s.modulars=[{id:'m1',department:'14',category:'1',description:'Test',sections:2,minutes:120,completed:false,dueDate:''}];const d=createDay(s,'2026-09-14',shifts());d.tasks[0].progress=50;d.reviewed=true;s.days.push(d);const next=createDay(s,'2026-09-15',shifts());assert.equal(next.tasks.length,1);assert.equal(next.tasks[0].minutes,60);});
test('reshops assign only eligible working people during configured windows',()=>{const s=fixture();s.settings.routines.reshops.enabled=true;s.settings.reshopWindows=[{start:960,end:1020}];const sf=shifts();sf[1].end=1080;const d=createDay(s,'2026-09-14',sf);assert.equal(d.tasks[0].assignedTo,'p2');assert.equal(d.tasks[0].segments[0].start,960);});
test('department restrictions and explicit assignments do not silently reroute',()=>{const s=fixture();s.team[0].departments=['14'];s.team[1].departments=['17'];const d=scheduleDay(s,plan([taskBase({department:'17',assignee:'p1'})]));assert.equal(d.tasks[0].assignedTo,'');assert.throws(()=>manualPlacement(s,d,d.tasks[0].id,'p1',420),/department/);});
test('manual placement rejects overlapping tasks and meal breaks',()=>{const s=fixture(),d=scheduleDay(s,plan([taskBase({minutes:60,assignee:'p1'}),taskBase({minutes:30,assignee:'p2'})]));assert.throws(()=>manualPlacement(s,d,d.tasks[1].id,'p1',430),/overlaps/);assert.throws(()=>manualPlacement(s,d,d.tasks[1].id,'p1',660),/overlaps/);const t=manualPlacement(s,d,d.tasks[1].id,'p1',720);assert.equal(t.locked,true);});
test('associate zoning metric uses recorded partial completion and actual-time denominator',()=>{const s=fixture();s.days=[plan([taskBase({kind:'zone',assignedTo:'p1',progress:100,status:'done',minutes:20,actualMinutes:30}),taskBase({kind:'zone',assignedTo:'p1',progress:50,minutes:20})])];const m=personMetrics(s,'p1');assert.equal(m.zone,75);assert.equal(m.completion,50);assert.equal(m.actualRatio,150);assert.equal(personMetrics(s,'p2').zone,null);});
test('repeating tasks honor weekday and availability; validated backup round-trips',()=>{const s=fixture();s.repeats=[{id:'r1',title:'Weekly check',minutes:30,department:'',priority:'normal',assignee:'',days:[1],active:true}];s.days.push(createDay(s,'2026-09-14',shifts()));assert.equal(s.days[0].tasks.length,1);const result=validateState(JSON.parse(JSON.stringify(s)));assert.equal(result.days[0].tasks[0].title,'Weekly check');const bad=structuredClone(s);bad.days[0].tasks[0].minutes=-1;assert.throws(()=>validateState(bad));});
test('local saves reject stale revisions and invalid data recovery starts setup',()=>{const map=new Map();globalThis.localStorage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const first=saveWorkspace(fixture());assert.equal(first.revision,1);assert.throws(()=>saveWorkspace(fixture()),/Another tab/);map.set(STORAGE_KEY,'corrupt');assert.equal(loadWorkspace().corrupt,true);assert.equal(loadWorkspace().state.profile,null);});
