import test from 'node:test';
import assert from 'node:assert/strict';
import {dropStart,taskMenu} from '../src/planner-interactions.js';
import {movePlannerTask,taskBase} from '../src/engine.js';
import {initialState} from '../src/data.js';
function fixture(){const state=initialState();state.team=[{id:'one',departments:[]},{id:'two',departments:['14']}];const task=taskBase({department:'14',minutes:30,assignedTo:'one',segments:[{start:420,end:450}]});const day={reviewed:false,tasks:[task],shifts:['one','two'].map(personId=>({personId,start:420,end:960,mealStart:660,mealMinutes:60,breaks:[]}))};return {state,day,task};}
test('drop snapping preserves the grabbed offset and works after scrolling',()=>{assert.equal(dropStart(196,100,420,24),450);assert.equal(dropStart(196,-140,420,24),550);assert.equal(dropStart(101,100,420),420);assert.equal(dropStart(0,100,420),380);});
test('task menu offers actions appropriate to status and reviewed days',()=>{const pending=taskBase({locked:true});assert.deepEqual(taskMenu(pending,false).map(x=>x.action),['edit','start','complete','unpin','delete']);assert.deepEqual(taskMenu({...pending,status:'done'},false).map(x=>x.action),['edit','delete']);assert.deepEqual(taskMenu(pending,true).map(x=>x.action),['edit']);assert.ok(!taskMenu({...pending,status:'in-progress'},false).some(x=>['start','unpin'].includes(x.action)));});
test('dragging reassigns and pins a task without mutating the original day',()=>{const {state,day,task}=fixture();const next=movePlannerTask(state,day,task.id,'two',480);assert.equal(next.assignedTo,'two');assert.equal(next.assignee,'two');assert.equal(next.locked,true);assert.deepEqual(next.segments,[{start:480,end:510}]);assert.equal(task.assignedTo,'one');});
test('invalid drops reject meals, occupied time, deadlines and department mismatches',()=>{const {state,day,task}=fixture();assert.throws(()=>movePlannerTask(state,day,task.id,'two',650),/break/);day.tasks.push(taskBase({assignedTo:'two',segments:[{start:480,end:510}]}));assert.throws(()=>movePlannerTask(state,day,task.id,'two',490),/overlaps/);task.deadline=550;assert.throws(()=>movePlannerTask(state,day,task.id,'two',540),/required/);task.department='17';assert.throws(()=>movePlannerTask(state,day,task.id,'two',520),/department/);});
test('dragging cannot change reviewed, started or completed work',()=>{const {state,day,task}=fixture();day.reviewed=true;assert.throws(()=>movePlannerTask(state,day,task.id,'two',480),/read-only/);day.reviewed=false;for(const status of ['in-progress','done']){task.status=status;assert.throws(()=>movePlannerTask(state,day,task.id,'two',480),/not started/);}});
test('moving a split partial task schedules its remaining work as one block',()=>{const {state,day,task}=fixture();task.minutes=60;task.progress=50;task.segments=[{start:420,end:435},{start:450,end:465}];assert.deepEqual(movePlannerTask(state,day,task.id,'two',480).segments,[{start:480,end:510}]);});
