import {welcomeMarkup} from './welcome.js';
import {DEPARTMENTS,ROUTINES,WEEKDAYS,SOURCES,uid,today,addDays,monday,toMinutes,toTime,clockLabel,duration,initialState,deptName} from './data.js';
import {capacity,shiftBounds,pauses,taskBase,createDay,scheduleDay,generateTasks,integrateTour,manualPlacement,dayMetrics,personMetrics,topstockProgress,lastAisleWork,unreviewedDay,validateShifts,remaining} from './engine.js';
import {loadWorkspace,saveWorkspace,validateState,STORAGE_KEY,BACKUP_KEY} from './storage.js';
import {demoState} from './demo.js';

function formWindow(f){const a=f.get('windowStart'),b=f.get('windowEnd');if(!a&&!b)return undefined;if(!a||!b||a===b)throw Error('Enter both window times, with a different start and end.');return {start:toMinutes(a),end:toMinutes(b)};}
function submitForm(event){
 const form=event.target;if(!form.id)return;event.preventDefault();if(!form.reportValidity())return;const f=new FormData(form),id=form.dataset.id||'',value=name=>String(f.get(name)||'').trim(),number=name=>Number(f.get(name));
 try{
  if(form.id==='setup-form'){
   captureSetup();
   if(setupStep===0&&(!setupDraft.profile.name||!setupDraft.departments.length))throw Error('Enter your name and select at least one department.');
   if(setupStep===1){
    // Include labels still sitting in an Add aisles field when Continue is pressed.
    for(const input of form.querySelectorAll('[data-aisle-input]'))if(input.value.trim())addSetupAisles(input.dataset.aisleInput,input.value);
    if(setupDraft.departments.some(d=>!setupDraft.aisles.some(a=>a.department===d.id)))throw Error('Add at least one aisle to each selected department.');
   }
   if(setupStep===2&&setupDraft.team.some(p=>!p.name.trim()))throw Error('Enter a name for each associate.');
   if(setupStep<3){setupStep++;showSetup();return;}
   const next=structuredClone(setupDraft),lead=next.team.find(p=>p.id===next.profile.leadId);
   if(lead){lead.name=next.profile.name;lead.active=true;}else next.team.unshift({id:next.profile.leadId,name:next.profile.name,role:'Team lead',active:true,departments:[]});
   next.aisles=next.aisles.filter(a=>next.departments.some(d=>d.id===a.department));
   next.team.forEach(p=>p.departments=p.departments.filter(id=>next.departments.some(d=>d.id===id)));
   ['pinpoint','topstock','reshops','zone'].forEach(id=>next.settings.routines[id].enabled=f.getAll('starter-routine').includes(id));
   const old=state;state=next;if(!commit(()=>{},{force:!!loaded.corrupt&&!setupEditing})){state=old;return;}
   closeModal();toast('Your workspace is ready.');if(!setupEditing)newDayWizard();return;
  }
  if(form.id==='day-form'){
   const shifts=f.getAll('working').map(id=>({personId:id,start:toMinutes(value('start-'+id)),end:toMinutes(value('end-'+id)),mealStart:toMinutes(value('meal-'+id)),mealMinutes:number('meal-min-'+id),breaks:[0,1].filter(n=>value('break-'+n+'-'+id)).map(n=>({start:toMinutes(value('break-'+n+'-'+id)),minutes:number('break-min-'+n+'-'+id)}))}));
   const error=validateShifts(shifts);if(error)throw Error(error);const date=value('date');
   if(form.dataset.editing==='true'){
    const next=structuredClone(day());
    for(const t of next.tasks.filter(t=>t.status==='done'||t.status==='in-progress'||t.locked)){const s=shifts.find(s=>s.personId===t.assignedTo);if(!t.segments.length)continue;if(!s||t.segments.some(seg=>seg.start<shiftBounds(s).start||seg.end>shiftBounds(s).end||pauses(s).some(p=>seg.start<p.end&&p.start<seg.end)))throw Error('These shifts would conflict with completed, in-progress, or pinned work. Unpin or adjust that work first.');}
    next.shifts=shifts;if(!replaceDay(scheduleDay(state,next)))return;
   }else{const next=createDay(state,date,shifts);if(!commit(s=>s.days.push(next)))return;selectedDate=date;}
   filterPerson='';closeModal();view='planner';render();toast('Your daily plan is ready.');return;
  }
  if(form.id==='followup-form'){
   const next=structuredClone(day()),done=new Set(f.getAll('done'));
   for(const t of next.tasks){t.progress=done.has(t.id)?100:number('progress-'+t.id);t.status=t.progress===100?'done':'pending';t.actualMinutes=value('actual-'+t.id)?number('actual-'+t.id):undefined;}
   next.reviewed=true;
   if(!commit(s=>{s.days[s.days.findIndex(d=>d.date===next.date)]=next;for(const m of s.modulars){if(next.tasks.some(t=>t.modularId===m.id&&t.status==='done'))m.completed=true;}}))return;
   closeModal();toast('Follow-up saved. Unfinished work will carry into the next plan.');if(form.dataset.next==='true')newDayWizard();return;
  }
  if(form.id==='task-form'){
   if(!requireDay())return;
   const next=structuredClone(day()),old=next.tasks.find(t=>t.id===id),desired=value('status'),progress=desired==='done'?100:number('progress'),window=formWindow(f);
   if(!value('title'))throw Error('Enter a task name.');
   const t={...(old||taskBase({})),title:value('title'),minutes:number('minutes'),department:value('department'),assignee:value('assignee'),priority:value('priority'),notes:value('notes'),progress,actualMinutes:value('actualMinutes')?number('actualMinutes'):undefined,window,status:progress===100?'done':desired};
   const requestedStatus=t.status;
   const changed=!old||t.minutes!==old.minutes||t.department!==old.department||(t.assignee||'')!==(old.assignee||old.assignedTo||'')||JSON.stringify(window)!==JSON.stringify(old.window)||value('pinTime')!==(old.locked&&old.segments.length?toTime(old.segments[0].start):'');
   if(old)next.tasks[next.tasks.indexOf(old)]=t;else next.tasks.push(t);
   let result=next;
   if(changed||!t.assignedTo){
    t.status='pending';t.locked=false;t.progress=0;
    result=scheduleDay(state,next);
    if(value('pinTime')){if(!t.assignee)throw Error('Select an associate to pin a start time.');let start=toMinutes(value('pinTime'));const s=next.shifts.find(s=>s.personId===t.assignee);if(s&&start<s.start&&shiftBounds(s).end>1440)start+=1440;const placed=manualPlacement(state,result,t.id,t.assignee,start);result.tasks[result.tasks.findIndex(x=>x.id===t.id)]=placed;}
    const updated=result.tasks.find(x=>x.id===t.id);if(!updated)throw Error('There is no capacity for this automatic zone. Add it as a tour priority to keep it on the plan.');updated.status=requestedStatus;updated.progress=progress;
    if(requestedStatus!=='pending'&&!updated.assignedTo)throw Error('Assign this task to an available person before recording progress or completion.');
   }
   if(!commit(s=>{s.days[s.days.findIndex(d=>d.date===result.date)]=result;const saved=result.tasks.find(x=>x.id===t.id);if(saved.modularId){const m=s.modulars.find(m=>m.id===saved.modularId);if(m)m.completed=saved.status==='done';}}))return;
   closeModal();toast('Task saved.');return;
  }
  if(form.id==='tour-form'){
   if(!requireDay())return;const aisle=state.aisles.find(a=>a.id===value('aisleId')),kind=value('kind');
   if(kind==='zone'&&!aisle)throw Error('Choose an aisle for a zoning observation.');
   if(aisle&&value('department')&&aisle.department!==value('department'))throw Error('The selected aisle is in a different department.');
   if(!value('title'))throw Error('Add a short observation.');
   const note=taskBase({title:value('title'),kind,priority:value('priority'),department:aisle?.department||value('department'),aisleId:aisle?.id||'',minutes:number('minutes'),assignee:value('assignee'),notes:value('notes')});
   if(commit(s=>s.tourDraft.push(note)))toast('Observation added to your tour.');return;
  }
  if(form.id==='person-form'){
   if(!value('name')||!value('role'))throw Error('Enter a name and role.');
   const p={id:id||uid(),name:value('name'),role:value('role'),departments:f.getAll('departments'),active:id===state.profile.leadId||f.has('active')};
   if(commit(s=>{if(id)s.team[s.team.findIndex(p=>p.id===id)]=p;else s.team.push(p);if(id===s.profile.leadId)s.profile.name=p.name;})){closeModal();toast('Associate saved.');}return;
  }
  if(form.id==='aisle-form'){
   const label=value('label').toUpperCase(),department=value('department');if(!label)throw Error('Enter an aisle label.');
   if(state.aisles.some(a=>a.id!==id&&a.label.toUpperCase()===label&&a.department===department))throw Error('This department already has an aisle with that label.');
   const a={id:id||uid(),label,department,zoneMinutes:number('zoneMinutes'),topMinutes:number('topMinutes'),topstock:f.has('topstock')};
   if(commit(s=>{if(id)s.aisles[s.aisles.findIndex(a=>a.id===id)]=a;else s.aisles.push(a);})){closeModal();toast('Aisle saved.');}return;
  }
  if(form.id==='routine-form'){
   const next=structuredClone(state.settings),cfg=next.routines[id];cfg.enabled=f.has('enabled');cfg.minutes=number('minutes');
   if(!['rfid','topstock','zone','reshops','modular'].includes(id)){cfg.days=f.getAll('days').map(Number);if(cfg.enabled&&!cfg.days.length)throw Error('Select at least one day.');}
   if(id==='zone'){next.zoneWindow={start:toMinutes(value('zoneStart')),end:toMinutes(value('zoneEnd'))};if(next.zoneWindow.start===next.zoneWindow.end)throw Error('Use different start and end times for zoning.');}
   if(id==='topstock'){next.topstockDays=f.getAll('topDays').map(Number);if(cfg.enabled&&!next.topstockDays.length)throw Error('Choose at least one top-stock day.');if(cfg.enabled&&!next.topstockDays.some(d=>d>=1&&d<=5))throw Error('Choose at least one Monday–Friday work day for the Friday target.');}
   if(id==='reshops'){const starts=f.getAll('reshopStart'),ends=f.getAll('reshopEnd');next.reshopWindows=starts.map((v,i)=>({start:toMinutes(v),end:toMinutes(ends[i])}));if(cfg.enabled&&!starts.length)throw Error('Add at least one reshop window.');if(next.reshopWindows.some(w=>w.start===w.end))throw Error('Use different start and end times for each reshop window.');}
   if(id==='rfid'){for(const d of state.departments){const enabled=f.getAll('rfidDept').includes(d.id),days=f.getAll('rfDays-'+d.id).map(Number);if(enabled&&!days.length)throw Error(`Select scan days for RFID department ${d.id}.`);next.rfid[d.id]={enabled,days};}}
   if(commit(s=>s.settings=next)){closeModal();toast('Routine settings saved for future plans.');}return;
  }
  if(form.id==='repeat-form'){
   const r={id:id||uid(),title:value('title'),minutes:number('minutes'),department:value('department'),assignee:value('assignee'),priority:value('priority'),days:f.getAll('days').map(Number),active:f.has('active'),window:formWindow(f)};
   if(!r.title||!r.days.length)throw Error('Enter a task name and choose at least one repeat day.');
   if(commit(s=>{if(id)s.repeats[s.repeats.findIndex(r=>r.id===id)]=r;else s.repeats.push(r);})){closeModal();toast('Repeating task saved.');}return;
  }
  if(form.id==='modular-form'){
   const m={id:id||uid(),department:value('department'),category:value('category'),description:value('description'),sections:number('sections'),minutes:number('minutes'),dueDate:value('dueDate'),completed:f.has('completed')};
   if(!m.category||!m.description)throw Error('Enter a category number and description.');
   if(commit(s=>{if(id)s.modulars[s.modulars.findIndex(m=>m.id===id)]=m;else s.modulars.push(m);})){closeModal();toast('Modular category saved.');}return;
  }
  if(form.id==='rebalance-form'){if(!requireDay())return;const next=scheduleDay(state,day(),{notBefore:toMinutes(value('fromTime'))});if(replaceDay(next)){closeModal();toast('Remaining tasks rebalanced.');}return;}
  if(form.id==='reset-form'){if(value('confirmation')!=='ERASE')throw Error('Type ERASE to confirm.');if(!demo){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(BACKUP_KEY);}state=initialState();demo=false;storageMessage='';selectedDate=today();view='overview';closeModal();render();setupWizard();return;}
 }catch(error){formError(error.message);}
}
function addSetupAisles(department,raw){for(const label of expandAisles(raw))if(!setupDraft.aisles.some(a=>a.department===department&&a.label.toUpperCase()===label))setupDraft.aisles.push({id:uid(),department,label,topstock:false,zoneMinutes:setupDraft.settings.routines.zone.minutes,topMinutes:setupDraft.settings.routines.topstock.minutes});}
function showDemo(){closeModal();demo=true;state=demoState();view='overview';selectedDate=today();selectedPerson='';filterPerson='';storageMessage='';render();}
function confirmAction(title,text,action,attrs=''){openModal(title,`<p>${text}</p><div class="modal-actions">${btn('Cancel','close-modal')}${btn('Confirm','confirm-'+action,'primary',attrs)}</div>`);}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`planit-${demo?'sample-':''}${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup downloaded. Keep it private.');}
let pendingImport=null;
function importBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;try{if(file.size>15*1024*1024)throw Error('The backup must be smaller than 15 MB.');pendingImport=validateState(JSON.parse(await file.text()));confirmAction('Restore this backup?',`Replace this workspace with <b>${esc(pendingImport.profile.name)}</b>’s backup: ${pendingImport.departments.length} departments, ${pendingImport.team.length} people, and ${pendingImport.days.length} planned days. Export your current workspace first if you need to keep it.`,'import');}catch(error){toast(error.message);}});input.click();}
function applyRoutines(){if(!requireDay())return;let next=structuredClone(day());next.tasks=next.tasks.filter(t=>t.source!=='routine'||t.status!=='pending'||t.locked||t.progress>0);const fresh=generateTasks(state,next).filter(t=>!next.tasks.some(old=>old.key===t.key||(t.aisleId&&old.aisleId===t.aisleId&&old.kind===t.kind)||(t.modularId&&old.modularId===t.modularId)));next.tasks.push(...fresh);if(replaceDay(scheduleDay(state,next)))toast('Pending routine work refreshed.');}
function clickAction(event){
 const button=event.target.closest('[data-action],#start-setup,#demo');if(!button)return;const action=button.dataset.action||(button.id==='demo'?'demo':'start-setup'),id=button.dataset.id;
 if(button.closest('form')&&button.type==='submit'&&!button.dataset.action)return;
 try{
  if(action==='close-modal'){closeModal();return;}
  if(action==='start-setup'||action==='edit-workspace'){setupWizard(action==='edit-workspace');return;}
  if(action==='demo'){showDemo();return;}
  if(action==='exit-demo'){const loaded=loadWorkspace();state=loaded.state;storageMessage=loaded.message;demo=false;selectedDate=state.days.at(-1)?.date||today();selectedPerson='';view='overview';render();return;}
  if(action==='navigate'){view=button.dataset.view;selectedPerson='';render();document.querySelector('#main')?.focus();return;}
  if(action==='setup-back'){captureSetup();setupStep--;showSetup();return;}
  if(action==='setup-add-department'){const number=modalRoot.querySelector('#custom-dept-id').value.trim(),name=modalRoot.querySelector('#custom-dept-name').value.trim();if(!/^\d{1,3}$/.test(number)||!name)throw Error('Enter a department number and name.');captureSetup();if(setupDraft.departments.some(d=>d.id===String(Number(number))))throw Error('That department is already selected.');setupDraft.departments.push({id:String(Number(number)),name});showSetup();return;}
  if(action==='setup-add-aisles'){captureSetup();const input=[...modalRoot.querySelectorAll('[data-aisle-input]')].find(i=>i.dataset.aisleInput===button.dataset.department);addSetupAisles(button.dataset.department,input.value);showSetup();return;}
  if(action==='setup-remove-aisle'){captureSetup();setupDraft.aisles=setupDraft.aisles.filter(a=>a.id!==id);showSetup();return;}
  if(action==='setup-add-person'){captureSetup();const name=modalRoot.querySelector('#new-team-name').value.trim();if(!name)throw Error('Enter an associate name.');setupDraft.team.push({id:uid(),name,role:'Associate',active:true,departments:[]});showSetup();return;}
  if(action==='new-day'){newDayWizard();return;}
  if(action==='edit-shifts'){if(requireDay())showShifts(selectedDate,true);return;}
  if(action==='previous-date'||action==='next-date'){const dates=state.days.map(d=>d.date).sort(),i=dates.indexOf(selectedDate),next=action==='previous-date'?dates[i-1]||dates.filter(d=>d<selectedDate).at(-1):dates[i+1]||dates.find(d=>d>selectedDate);if(next){selectedDate=next;filterPerson='';render();}return;}
  if(action==='follow-up'){followUp();return;}
  if(action==='conduct-tour'){if(requireDay()){view='tour';render();}return;}
  if(action==='complete-tour'){if(!requireDay())return;if(!state.tourDraft.length){toast('Add at least one observation to complete your tour.');return;}const next=integrateTour(state,day(),state.tourDraft);if(commit(s=>{s.days[s.days.findIndex(d=>d.date===next.date)]=next;s.tourDraft=[];})){view='planner';render();toast('Tour integrated. Priorities assigned and routines rebalanced.');}return;}
  if(action==='remove-note'){commit(s=>s.tourDraft=s.tourDraft.filter(n=>n.id!==id));return;}
  if(action==='planner-mode'){plannerMode=button.dataset.mode;render();return;}
  if(action==='add-task'||action==='edit-task'){if(action==='edit-task'||requireDay())taskEditor(id);return;}
  if(action==='delete-task'){confirmAction('Delete this task?','This removes the task from this day and its completion metrics.','delete-task',`data-id="${id}"`);return;}
  if(action==='confirm-delete-task'){if(requireDay()){const next=structuredClone(day());next.tasks=next.tasks.filter(t=>t.id!==id);if(replaceDay(scheduleDay(state,next)))closeModal();}return;}
  if(action==='rebalance'){if(requireDay())openModal('Rebalance the remaining work',`<form id="rebalance-form"><p>Completed, in-progress, and pinned tasks stay in place. All other work will be assigned around shifts and breaks.</p><label>Schedule no earlier than<input name="fromTime" type="time" value="${toTime(Math.min(...day().shifts.map(s=>s.start)))}" required></label>${errorBox()}<div class="modal-actions"><span></span><button type="submit" class="btn primary">Rebalance plan</button></div></form>`);return;}
  if(action==='profile'){selectedPerson=id;view='team';render();return;}
  if(action==='back-team'){selectedPerson='';render();return;}
  if(action==='add-person'||action==='edit-person'){personEditor(id);return;}
  if(action==='add-aisle'||action==='edit-aisle'){aisleEditor(id,button.dataset.department);return;}
  if(action==='delete-aisle'){confirmAction('Remove this aisle?','Future automatic assignments will omit this aisle. Existing tasks and recorded history are kept.','delete-aisle',`data-id="${id}"`);return;}
  if(action==='confirm-delete-aisle'){if(commit(s=>s.aisles=s.aisles.filter(a=>a.id!==id)))closeModal();return;}
  if(action==='configure-routine'){routineEditor(id);return;}
  if(action==='add-reshop-window'){modalRoot.querySelector('#reshop-windows').insertAdjacentHTML('beforeend',reshopWindowRow({start:900,end:960},0));return;}
  if(action==='remove-reshop-window'){button.closest('.window-row').remove();return;}
  if(action==='apply-routines'){applyRoutines();return;}
  if(action==='add-repeat'||action==='edit-repeat'){repeatEditor(id);return;}
  if(action==='delete-repeat'){if(commit(s=>s.repeats=s.repeats.filter(r=>r.id!==id)))closeModal();return;}
  if(action==='add-modular'||action==='edit-modular'){modularEditor(id);return;}
  if(action==='delete-modular'){confirmAction('Delete this modular category?','Remove this category from future plans. Existing tasks remain on their original days.','delete-modular',`data-id="${id}"`);return;}
  if(action==='confirm-delete-modular'){if(commit(s=>s.modulars=s.modulars.filter(m=>m.id!==id)))closeModal();return;}
  if(action==='export'){exportBackup();return;}
  if(action==='import'){importBackup();return;}
  if(action==='confirm-import'){if(!pendingImport)return;const old=state;state={...pendingImport,revision:old.revision};if(commit(()=>{},{force:true})){pendingImport=null;selectedDate=state.days.at(-1)?.date||today();view='overview';selectedPerson='';closeModal();render();toast('Backup restored.');}else state=old;return;}
  if(action==='recover'){const raw=localStorage.getItem(BACKUP_KEY);if(!raw)throw Error('No local recovery snapshot is available. Restore an exported backup instead.');pendingImport=validateState(JSON.parse(raw));confirmAction('Recover the previous local save?',`Restore ${esc(pendingImport.profile.name)}’s last recovery snapshot (${pendingImport.days.length} planned days). This replaces the current workspace.`,'import');return;}
  if(action==='reset'){openModal('Erase this workspace?',`<p>This removes names, shifts, notes, aisle history, and the recovery snapshot from this browser. Export a backup first if you want to keep them.</p><form id="reset-form"><label>Type ERASE to confirm<input name="confirmation" autocomplete="off" required></label>${errorBox()}<div class="modal-actions"><button type="button" class="btn" data-action="close-modal">Cancel</button><button type="submit" class="btn danger">Erase local data</button></div></form>`);return;}
 }catch(error){formError(error.message);}
}
function initialize(){
 render();document.addEventListener('click',clickAction);document.addEventListener('submit',submitForm);
 document.addEventListener('change',event=>{
  const el=event.target;
  if(el.closest('#followup-form')){
   const row=el.closest('.followup-row');
   if(row&&el.name==='done'){const progress=row.querySelector('input[name^="progress-"]');if(el.checked)progress.value='100';else if(progress.value==='100')progress.value='0';}
   if(row&&el.name.startsWith('progress-'))row.querySelector('input[name="done"]').checked=Number(el.value)===100;
  }
  if(el.closest('#task-form')){
   const form=el.closest('form'),progress=form.querySelector('[name="progress"]'),status=form.querySelector('[name="status"]');
   if(el.name==='status'){if(status.value==='done')progress.value='100';else if(progress.value==='100')progress.value='0';}
   if(el.name==='progress'){if(Number(progress.value)===100)status.value='done';else if(status.value==='done')status.value=Number(progress.value)>0?'in-progress':'pending';}
  }
  if(el.dataset.setupTop){setupDraft.aisles.find(a=>a.id===el.dataset.setupTop).topstock=el.checked;return;}
  if(el.dataset.setupActive){setupDraft.team.find(p=>p.id===el.dataset.setupActive).active=el.checked;return;}
  if(el.dataset.routineToggle){const id=el.dataset.routineToggle,enabled=el.checked;if(commit(s=>s.settings.routines[id].enabled=enabled)&&enabled&&['rfid','zone','reshops','topstock'].includes(id))routineEditor(id);return;}
  if(el.id==='plan-date'&&el.value){selectedDate=el.value;filterPerson='';render();return;}
  if(el.id==='person-filter'){filterPerson=el.value;render();return;}
  if(el.id==='status-filter'){filterStatus=el.value;render();return;}
  if(el.id==='metric-range'){metricRange=el.value;render();return;}
 });
 document.addEventListener('input',event=>{if(event.target.id==='department-search'){const q=event.target.value.trim().toLowerCase();modalRoot.querySelectorAll('[data-dept-search]').forEach(el=>el.hidden=!el.dataset.deptSearch.includes(q));}});
 document.addEventListener('dragstart',event=>{const el=event.target.closest('[data-task]');if(el)event.dataTransfer.setData('text/planit-task',el.dataset.task);});
 document.addEventListener('dragover',event=>{if(event.target.closest('.person-lane'))event.preventDefault();});
 document.addEventListener('drop',event=>{const lane=event.target.closest('.person-lane');if(!lane)return;event.preventDefault();const id=event.dataTransfer.getData('text/planit-task');if(!id||!requireDay())return;try{const start=Number(lane.dataset.start)+Math.round((event.clientY-lane.getBoundingClientRect().top)/2.4/5)*5,task=manualPlacement(state,day(),id,lane.dataset.person,start);if(saveDayTask(task))toast('Task moved and pinned.');}catch(error){toast(error.message);}});
 window.addEventListener('storage',event=>{if(!demo&&event.key===STORAGE_KEY){storageMessage='This workspace changed in another tab. Reload before making edits to avoid overwriting changes.';render();}});
 window.addEventListener('hashchange',()=>{if(location.hash==='#overview'&&state.profile){view='overview';render();}});
 if('serviceWorker' in navigator&&location.hostname!=='127.0.0.1'&&location.hostname!=='localhost')navigator.serviceWorker.register('./sw.js').catch(()=>toast('Offline caching is unavailable. Your workspace still saves locally.'));
 if(!state.profile&&!storageMessage)setupWizard();
 else if(state.profile&&(!state.days.length||state.days.map(d=>d.date).sort().at(-1)<today()))newDayWizard();
 registerAgentTools();
}
function registerAgentTools(){
 // No workspace-reading tool is registered: private names and records stay out of agent tool results.
 const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
 const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'planit_open_view',title:'Open PlanIt view',description:'Navigate to a PlanIt view. Does not read or return private workspace records.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['overview','planner','tour','team','aisles','routines','settings']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!['overview','planner','tour','team','aisles','routines','settings'].includes(input.view)||Object.keys(input).some(k=>k!=='view'))throw Error('Invalid view.');if(!state.profile)throw Error('Complete workspace setup first.');view=input.view;selectedPerson='';render();return {opened:view};}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
queueMicrotask(initialize);

function setupWizard(edit=false){setupEditing=edit;setupStep=0;setupDraft=structuredClone(state);if(!setupDraft.profile)setupDraft.profile={name:'',leadId:uid()};showSetup();}
function showSetup(){
 const draft=setupDraft;
 const steps=['Your departments','Aisles & top stock','Your team','Ready to plan'];
 let content=`<div class="wizard-progress">${steps.map((s,i)=>`<span class="${i<=setupStep?'active':''}"><b>${i+1}</b>${s}</span>`).join('')}</div><form id="setup-form" data-step="${setupStep}">`;
 if(setupStep===0){const refs=[...DEPARTMENTS,...draft.departments.filter(d=>!DEPARTMENTS.some(r=>r.id===d.id))];content+=`<p>Start with your name and the departments you’re responsible for.</p><label>Your name<input name="leadName" value="${esc(draft.profile.name)}" maxlength="100" required autocomplete="given-name" placeholder="What should we call you?"></label><label class="block-label">Your departments</label><input id="department-search" type="search" placeholder="Search number or department" aria-label="Search departments"><div class="department-picker">${refs.map(d=>`<label data-dept-search="${esc((d.id+' '+d.name).toLowerCase())}"><input type="checkbox" name="departments" value="${esc(d.id)}"${checked(draft.departments.some(x=>x.id===d.id))}><b>${esc(d.id.padStart(2,'0'))}</b><span>${esc(draft.departments.find(x=>x.id===d.id)?.name||d.name)}</span></label>`).join('')}</div><details><summary>My department isn’t listed</summary><div class="form-grid custom-dept"><label>Number<input id="custom-dept-id" type="text" maxlength="10" placeholder="e.g. 68"></label><label>Name<input id="custom-dept-name" maxlength="100" placeholder="Department name"></label></div><button type="button" class="btn" data-action="setup-add-department">Add department</button></details><p class="helper">Public department labels are a starting point. You can adjust them to match your store.</p>`;}
 if(setupStep===1){content+=`<p>Add your aisle labels. Tick each aisle that has top stock.</p>`+draft.departments.map(d=>`<section class="setup-department"><label class="dept-title"><span class="department-number">${esc(d.id)}</span><input name="deptName-${esc(d.id)}" value="${esc(d.name)}" maxlength="100" required aria-label="Department ${esc(d.id)} name"></label><div class="inline-input"><input data-aisle-input="${esc(d.id)}" placeholder="e.g. H1, H2, H3 or H1-H8" maxlength="500" aria-label="Aisles for department ${esc(d.id)}"><button class="btn" type="button" data-action="setup-add-aisles" data-department="${esc(d.id)}">Add aisles</button></div><div class="setup-aisle-list">${draft.aisles.filter(a=>a.department===d.id).map(a=>`<div class="setup-aisle"><b>${esc(a.label)}</b><label><input type="checkbox" data-setup-top="${a.id}"${checked(a.topstock)}> Top stock</label><button type="button" data-action="setup-remove-aisle" data-id="${a.id}" aria-label="Remove aisle ${esc(a.label)}">×</button></div>`).join('')}</div></section>`).join('');}
 if(setupStep===2)content+=`<p>You’re included as the team lead. Add the associates you plan for; you’ll choose who is working each day.</p><div class="lead-row">${icon('team')} <b>${esc(draft.profile.name)}</b> ${chip('Team lead','green')}</div><div class="inline-input"><input id="new-team-name" maxlength="100" placeholder="Associate’s name" aria-label="Associate name"><button type="button" class="btn" data-action="setup-add-person">Add associate</button></div><div class="setup-team-list">${draft.team.filter(p=>p.id!==draft.profile.leadId).map(p=>`<div class="setup-person"><label class="sr-only" for="person-${p.id}">Associate name</label><input id="person-${p.id}" name="person-${p.id}" value="${esc(p.name)}" maxlength="100" required><label><input type="checkbox" data-setup-active="${p.id}"${checked(p.active)}> Active</label></div>`).join('')}</div><p class="helper">Department restrictions, role labels, and archived associates can be managed in My team.</p>`;
 if(setupStep===3)content+=`<div class="setup-done-mark">${icon('check',32)}</div><h3>You’re ready, ${esc(draft.profile.name.split(' ')[0])}.</h3><p>${draft.departments.length} departments · ${draft.aisles.length} aisles · ${draft.team.filter(p=>p.active&&p.id!==draft.profile.leadId).length+1} people</p><fieldset class="starter-routines"><legend>Start with these routines</legend>${['pinpoint','topstock','reshops','zone'].map(id=>`<label><input type="checkbox" name="starter-routine" value="${id}"${checked(draft.settings.routines[id].enabled)}> ${ROUTINES.find(r=>r.id===id).name}</label>`).join('')}</fieldset><p class="helper">Default zoning is 2–4 pm; reshops are 10–11 am and 1–2 pm. Change windows, estimates, and scan days in Routines. All personal data stays on this device.</p>`;
 content+=`${errorBox()}<div class="modal-actions">${setupStep?'<button type="button" class="btn" data-action="setup-back">Back</button>':'<span></span>'}<button type="submit" class="btn primary">${setupStep===3?(setupEditing?'Save workspace':'Create my workspace'):'Continue '+icon('arrow',16)}</button></div></form>`;openModal(setupEditing?'Edit your workspace':'Set up your workspace',content,true);
}
function captureSetup(){
 const form=modalRoot.querySelector('#setup-form');if(!form)return;
 const f=new FormData(form);
 if(setupStep===0){setupDraft.profile.name=String(f.get('leadName')||'').trim();const ids=f.getAll('departments');const refs=[...DEPARTMENTS,...setupDraft.departments.filter(d=>!DEPARTMENTS.some(r=>r.id===d.id))];setupDraft.departments=ids.map(id=>setupDraft.departments.find(d=>d.id===id)||refs.find(d=>d.id===id));}
 if(setupStep===1)setupDraft.departments.forEach(d=>{d.name=String(f.get('deptName-'+d.id)||d.name).trim();});
 if(setupStep===2)setupDraft.team.forEach(p=>{if(f.has('person-'+p.id))p.name=String(f.get('person-'+p.id)).trim();});
}
function expandAisles(raw){const out=[];for(const token of raw.split(/[,\n]+/).map(s=>s.trim().toUpperCase()).filter(Boolean)){const match=token.match(/^([A-Z]*)(\d+)\s*-\s*([A-Z]*)(\d+)$/);if(match&&(!match[3]||match[1]===match[3])){const from=Number(match[2]),to=Number(match[4]);if(to<from||to-from>200)throw Error('Use an ascending range of no more than 201 aisles.');for(let i=from;i<=to;i++)out.push(match[1]+i);}else{if(token.length>40)throw Error('Aisle labels must be 40 characters or fewer.');out.push(token);}}return [...new Set(out)];}
function newDayWizard(){
 if(!state.profile){setupWizard();return;}
 const pending=unreviewedDay(state);if(pending){selectedDate=pending.date;render();followUp(true);return;}
 const latest=state.days.map(d=>d.date).sort().at(-1);let date=selectedDate;
 if(state.days.some(d=>d.date===date)||latest&&date<=latest)date=latest>=today()?addDays(latest,1):today();
 showShifts(date,false);
}
function showShifts(date,editing=false){
 const previous=editing?day():state.days.at(-1),roster=state.team.filter(p=>p.active||editing&&previous?.shifts.some(s=>s.personId===p.id));
 const content=`<p>${editing?'Update who’s working and their availability. Completed, started, and pinned work must still fit.':'Choose who’s working. Then set shift times, meals, and optional rest breaks.'}</p><form id="day-form" data-editing="${editing}"><label>Plan date<input name="date" type="date" value="${date}" required ${editing?'readonly':''}></label><p class="helper">An end time before the start means the shift ends the next day. Meal and break times must fit inside the shift. Set meal length to 0 to omit it.</p><div class="shift-editor">${roster.map((p,i)=>{const old=previous?.shifts.find(s=>s.personId===p.id),s=old||{start:420,end:960,mealStart:660+i*15,mealMinutes:60,breaks:[]};return `<fieldset class="shift-person" data-shift-person="${p.id}"><legend><label><input type="checkbox" name="working" value="${p.id}"${checked(editing?!!old:p.active)}> ${esc(p.name)} <small>${esc(p.role)}</small></label></legend><div class="shift-fields"><label>Start<input type="time" name="start-${p.id}" value="${toTime(s.start)}" required></label><label>End<input type="time" name="end-${p.id}" value="${toTime(s.end)}" required></label><label>Meal starts<input type="time" name="meal-${p.id}" value="${toTime(s.mealStart)}" required></label><label>Meal (min)<input type="number" name="meal-min-${p.id}" min="0" max="120" step="5" value="${s.mealMinutes}" required></label></div><details><summary>Rest breaks ${s.breaks.length?'('+s.breaks.length+')':'(optional)'}</summary><div class="shift-fields">${[0,1].map(n=>`<label>Break ${n+1} starts<input type="time" name="break-${n}-${p.id}" value="${s.breaks[n]?toTime(s.breaks[n].start):''}"></label><label>Minutes<input type="number" name="break-min-${n}-${p.id}" min="5" max="60" step="5" value="${s.breaks[n]?.minutes||15}"></label>`).join('')}</div></details></fieldset>`;}).join('')}</div>${errorBox()}<div class="modal-actions"><button type="button" class="btn" data-action="close-modal">Cancel</button><button type="submit" class="btn primary">${editing?'Save shifts & rebalance':'Build daily plan '+icon('arrow',16)}</button></div></form>`;
 openModal(editing?'Who’s working?':'Set up your day',content,true);
}
function followUp(openNext=false){
 const d=day();if(!d||d.reviewed){if(openNext)newDayWizard();else toast('This day has already been followed up.');return;}
 if(state.tourDraft.length){toast('Complete your draft tour before following up so its notes are included.');view='tour';render();return;}
 openModal(`Follow up · ${formatDate(d.date,{month:'short',day:'numeric'})}`,`<p>Confirm completed work. For unfinished tasks, record how far you got; the remaining estimate is re-added to the next day.</p><form id="followup-form" data-next="${openNext}"><div class="followup-list">${d.tasks.map(t=>`<div class="followup-row"><label class="followup-title"><input type="checkbox" name="done" value="${t.id}"${checked(t.status==='done')}> <span><b>${esc(t.title)}</b><small>${esc(person(t.assignedTo)?.name||'Unassigned')} · ${duration(t.minutes)}</small></span></label><label>Progress %<input type="number" name="progress-${t.id}" min="0" max="100" step="5" value="${t.progress||0}"></label><label>Actual minutes<input type="number" name="actual-${t.id}" min="1" max="2000" value="${t.actualMinutes||''}" placeholder="Optional"></label></div>`).join('')}</div><label class="check-line review-confirm"><input name="confirm" type="checkbox" required> I reviewed every task. Re-add all unfinished work to the next plan.</label>${errorBox()}<div class="modal-actions"><button type="button" class="btn" data-action="close-modal">Go back</button><button type="submit" class="btn primary">${openNext?'Confirm & set up next day':'Complete follow-up'}</button></div></form>`,true);
}
function taskEditor(id=''){
 if(!day()){newDayWizard();return;}
 const t=day().tasks.find(t=>t.id===id)||taskBase({}),isNew=!id,readonly=day().reviewed;
 openModal(isNew?'Add a task':esc(t.title),`<form id="task-form" data-id="${id}"><fieldset ${readonly?'disabled':''} class="plain-fieldset"><label>Task name<input name="title" maxlength="300" value="${esc(t.title==='Task'?'':t.title)}" required></label><div class="form-grid"><label>Estimate (minutes)<input type="number" name="minutes" min="1" max="960" step="1" value="${t.minutes}" required></label><label>Priority<select name="priority">${['urgent','high','normal','low'].map(p=>`<option${selected(t.priority,p)}>${p}</option>`).join('')}</select></label><label>Department<select name="department">${deptOptions(t.department)}</select></label><label>Assign to<select name="assignee">${personOptions(t.assignee||t.assignedTo,true)}</select></label><label>Status<select name="status"><option value="pending"${selected(t.status,'pending')}>To do</option><option value="in-progress"${selected(t.status,'in-progress')}>In progress</option><option value="done"${selected(t.status,'done')}>Completed</option></select></label><label>Completion %<input name="progress" type="number" min="0" max="100" step="5" value="${t.progress}"></label><label>Actual minutes<input name="actualMinutes" type="number" min="1" max="2000" value="${t.actualMinutes||''}" placeholder="Optional"></label><label>Pin to start time<input name="pinTime" type="time" value="${t.locked&&t.segments.length?toTime(t.segments[0].start):''}"></label></div><details ${t.window?'open':''}><summary>Scheduling window</summary><p class="helper">Leave both blank for any time in the shift. A pinned time must fit without overlaps.</p><div class="form-grid"><label>Earliest start<input name="windowStart" type="time" value="${t.window?toTime(t.window.start):''}"></label><label>Finish by<input name="windowEnd" type="time" value="${t.window?toTime(t.window.end):''}"></label></div></details><label>Notes<textarea name="notes" rows="3" maxlength="5000">${esc(t.notes)}</textarea></label>${t.segments.length?`<p class="helper">Scheduled: ${t.segments.map(s=>clockLabel(s.start)+'–'+clockLabel(s.end)).join(', ')}${t.segments.length>1?' (split around breaks or other work)':''}</p>`:''}${t.unscheduledReason?`<p class="helper amber-text">${esc(t.unscheduledReason)}</p>`:''}</fieldset>${errorBox()}<div class="modal-actions">${!isNew&&!readonly?btn('Delete task','delete-task','danger','type="button" data-id="'+t.id+'"'):'<span></span>'}${readonly?btn('Close','close-modal','primary','type="button"'):'<button type="submit" class="btn primary">'+(isNew?'Add & schedule':'Save changes')+'</button>'}</div></form>`,true);
}
function personEditor(id=''){
 const p=person(id)||{name:'',role:'Associate',active:true,departments:[]};
 openModal(id?'Edit associate':'Add associate',`<form id="person-form" data-id="${id}"><label>Name<input name="name" value="${esc(p.name)}" maxlength="100" required></label><label>Role<input name="role" value="${esc(p.role)}" maxlength="100" required></label><fieldset><legend>Departments they can work</legend><p class="helper">Leave all unchecked to allow every department you manage.</p>${state.departments.map(d=>`<label class="check-line"><input type="checkbox" name="departments" value="${d.id}"${checked(p.departments.includes(d.id))}> D${esc(d.id)} · ${esc(d.name)}</label>`).join('')}</fieldset><label class="check-line"><input type="checkbox" name="active"${checked(p.active)} ${id===state.profile.leadId?'disabled':''}> Active on the team</label><p class="helper">Archiving an associate removes them from future day setup while keeping their history.</p>${errorBox()}<div class="modal-actions"><span></span><button class="btn primary" type="submit">Save associate</button></div></form>`);
}
function aisleEditor(id='',department=''){
 const a=state.aisles.find(a=>a.id===id)||{label:'',department:department||state.departments[0].id,topstock:false,zoneMinutes:state.settings.routines.zone.minutes,topMinutes:state.settings.routines.topstock.minutes};
 openModal(id?'Edit aisle':'Add aisle',`<form id="aisle-form" data-id="${id}"><div class="form-grid"><label>Aisle label<input name="label" value="${esc(a.label)}" maxlength="40" required placeholder="e.g. H12"></label><label>Department<select name="department">${deptOptions(a.department,false)}</select></label><label>Zone estimate (min)<input name="zoneMinutes" type="number" min="5" max="480" step="5" value="${a.zoneMinutes}" required></label><label>Top-stock estimate (min)<input name="topMinutes" type="number" min="5" max="480" step="5" value="${a.topMinutes}" required></label></div><label class="check-line"><input type="checkbox" name="topstock"${checked(a.topstock)}> This aisle has top stock</label>${errorBox()}<div class="modal-actions">${id?btn('Remove aisle','delete-aisle','danger','type="button" data-id="'+id+'"'):'<span></span>'}<button class="btn primary" type="submit">Save aisle</button></div></form>`);
}
function routineEditor(id){
 const r=ROUTINES.find(r=>r.id===id),cfg=state.settings.routines[id];let extra='';
 if(id==='zone')extra=`<div class="form-grid"><label>Zoning starts<input name="zoneStart" type="time" value="${toTime(state.settings.zoneWindow.start)}" required></label><label>Zoning ends<input name="zoneEnd" type="time" value="${toTime(state.settings.zoneWindow.end)}" required></label></div><p class="helper">The window and shift capacity determine how many aisles fit. Oldest completed zones come first. Individual aisle estimates are editable in Aisles & departments.</p>`;
 if(id==='topstock')extra=`<label class="block-label">Top-stock work days</label>${daysPicker('topDays',state.settings.topstockDays)}<p class="helper">Remaining aisles are divided over your selected work days through Friday. Assignments are balanced between available, eligible people. Capacity shortfalls stay visible; a Friday finish needs enough staffed time.</p>`;
 if(id==='reshops')extra=`<label class="block-label">Daily reshop windows</label><div id="reshop-windows">${state.settings.reshopWindows.map((w,i)=>reshopWindowRow(w,i)).join('')}</div><button type="button" class="btn" data-action="add-reshop-window">Add window</button><p class="helper">One task is assigned within each window to a person working then. Use the estimate above for each run.</p>`;
 if(id==='rfid')extra=`<p class="helper">Tick RFID for each participating department and choose its scan days. All other departments receive a deep out scan every Tuesday.</p>${state.departments.map(d=>{const cfg=state.settings.rfid[d.id]||{enabled:false,days:[]};return `<fieldset><legend>D${esc(d.id)} · ${esc(d.name)}</legend><label class="check-line"><input type="checkbox" name="rfidDept" value="${d.id}"${checked(cfg.enabled)}> Uses RFID instead of deep outs</label>${daysPicker('rfDays-'+d.id,cfg.days)}</fieldset>`;}).join('')}`;
 if(id==='modular')extra='<p class="helper">Each category uses its own estimate and due date. Set up categories below the routine library. This default is only a starting estimate for new categories.</p>';
 openModal(r.name+' settings',`<form id="routine-form" data-id="${id}"><label class="check-line"><input type="checkbox" name="enabled"${checked(cfg.enabled)}> Enable ${r.name}</label><label>${['zone','topstock','modular'].includes(id)?'Default estimate for new aisles / categories':'Estimated minutes per task'}<input name="minutes" type="number" min="5" max="480" step="5" value="${cfg.minutes}" required></label>${!['rfid','topstock','zone','reshops','modular'].includes(id)?`<label class="block-label">Repeat on</label>${daysPicker('days',cfg.days)}`:''}${extra}${errorBox()}<div class="modal-actions"><button type="button" class="btn" data-action="close-modal">Cancel</button><button class="btn primary" type="submit">Save settings</button></div></form>`,id==='rfid');
}
function reshopWindowRow(w,i){return `<div class="window-row"><label>From<input type="time" name="reshopStart" value="${toTime(w.start)}" required></label><label>Until<input type="time" name="reshopEnd" value="${toTime(w.end)}" required></label><button class="icon-btn" type="button" data-action="remove-reshop-window" aria-label="Remove reshop window">${icon('close',17)}</button></div>`;}
function repeatEditor(id=''){
 const r=state.repeats.find(r=>r.id===id)||{title:'',minutes:30,department:'',assignee:'',priority:'normal',days:[1,2,3,4,5],active:true};
 openModal(id?'Edit repeating task':'Add repeating task',`<form id="repeat-form" data-id="${id}"><label>Task name<input name="title" maxlength="300" value="${esc(r.title)}" required></label><div class="form-grid"><label>Estimate (minutes)<input name="minutes" type="number" min="5" max="960" step="5" value="${r.minutes}" required></label><label>Priority<select name="priority">${['urgent','high','normal','low'].map(p=>`<option${selected(p,r.priority)}>${p}</option>`).join('')}</select></label><label>Department<select name="department">${deptOptions(r.department)}</select></label><label>Assign to<select name="assignee">${personOptions(r.assignee)}</select></label><label>Window start (optional)<input name="windowStart" type="time" value="${r.window?toTime(r.window.start):''}"></label><label>Window end (optional)<input name="windowEnd" type="time" value="${r.window?toTime(r.window.end):''}"></label></div><label class="block-label">Repeat on</label>${daysPicker('days',r.days)}<label class="check-line"><input name="active" type="checkbox"${checked(r.active)}> Active</label>${errorBox()}<div class="modal-actions">${id?btn('Delete repeat','delete-repeat','danger','type="button" data-id="'+id+'"'):'<span></span>'}<button type="submit" class="btn primary">Save repeating task</button></div></form>`);
}
function modularEditor(id=''){
 const m=state.modulars.find(m=>m.id===id)||{department:state.departments[0].id,category:'',description:'',sections:1,minutes:state.settings.routines.modular.minutes,dueDate:'',completed:false};
 openModal(id?'Edit modular category':'Add modular category',`<form id="modular-form" data-id="${id}"><div class="form-grid"><label>Department<select name="department">${deptOptions(m.department,false)}</select></label><label>Category number<input name="category" maxlength="50" value="${esc(m.category)}" required placeholder="e.g. 0231"></label></div><label>Description<input name="description" maxlength="300" value="${esc(m.description)}" required></label><div class="form-grid"><label>Number of sections<input name="sections" type="number" min="1" max="500" value="${m.sections}" required></label><label>Estimate (minutes)<input name="minutes" type="number" min="5" max="960" step="5" value="${m.minutes}" required></label><label>Due date (optional)<input name="dueDate" type="date" value="${m.dueDate}"></label><label class="check-line"><input name="completed" type="checkbox"${checked(m.completed)}> Completed</label></div><p class="helper">The category is eligible on its due date, or the next plan if undated. Longer work can be split around breaks. Unfinished work carries forward.</p>${errorBox()}<div class="modal-actions">${id?btn('Delete category','delete-modular','danger','type="button" data-id="'+id+'"'):'<span></span>'}<button type="submit" class="btn primary">Save category</button></div></form>`);
}

const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root'),loaded=loadWorkspace();
let state=loaded.state,storageMessage=loaded.message,demo=false,view='overview',selectedDate=state.days.at(-1)?.date||today(),selectedPerson='',metricRange='30',plannerMode='timeline',filterPerson='',filterStatus='all',setupDraft=null,setupStep=0,setupEditing=false,modalReturnFocus=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const selected=(a,b)=>a===b?' selected':'',checked=v=>v?' checked':'';
const day=()=>state.days.find(d=>d.date===selectedDate),person=id=>state.team.find(p=>p.id===id);
const initials=name=>name.split(/\s+/).map(n=>n[0]).slice(0,2).join('').toUpperCase(),percent=(n,d)=>d?Math.round(n/d*100):0;
const formatDate=(date,options={weekday:'long',month:'long',day:'numeric'})=>new Date(date+'T12:00:00').toLocaleDateString(undefined,options);
const icons={overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',planner:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18M8 15h2M14 15h2"/>',tour:'<path d="M9 5H5v16h14V5h-4M9 3h6v4H9zM8 12h8M8 16h5"/>',team:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 5v2"/>',aisles:'<path d="M4 3v18M20 3v18M4 9h16M4 17h16M8 4v5M15 12v5"/>',routines:'<path d="M20 7a8 8 0 1 0 1 9M20 3v5h-5M12 7v5l3 2"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',check:'<path d="m5 12 4 4L19 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',spark:'<path d="m12 3 2 6 7 3-7 2-2 7-2-7-7-2 7-3z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',warning:'<path d="m12 3 10 18H2zM12 9v5M12 17h.01"/>'};
const icon=(name,size=19)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.check}</svg>`;
const btn=(text,action,classes='',attrs='')=>`<button class="btn ${classes}" data-action="${action}" ${attrs}>${text}</button>`;
const avatar=(p,small=false)=>`<span class="avatar ${small?'small':''} color-${Math.max(0,state.team.findIndex(x=>x.id===p?.id))%5}" aria-hidden="true">${esc(initials(p?.name||'?'))}</span>`;
const chip=(label,cls='')=>`<span class="chip ${cls}">${esc(label)}</span>`;
const empty=(title,desc,action='')=>`<div class="empty-state"><span class="empty-icon">${icon('planner',30)}</span><h3>${esc(title)}</h3><p>${esc(desc)}</p>${action}</div>`;
const sectionHeader=(title,sub='',action='')=>`<div class="section-heading"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${action}</div>`;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),5000);}
function commit(mutator,{force=false}={}){const next=structuredClone(state);mutator(next);try{validateState(next);state=demo||loaded.unavailable?next:saveWorkspace(next,{force});storageMessage=loaded.unavailable?'Browser storage is unavailable. This workspace is temporary; export before leaving.':'';render();return true;}catch(error){toast(error.message);return false;}}
function replaceDay(next){return commit(s=>{s.days[s.days.findIndex(d=>d.date===next.date)]=next;});}
function saveDayTask(task){const next=structuredClone(day());next.tasks[next.tasks.findIndex(t=>t.id===task.id)]=task;return replaceDay(next);}
function requireDay(){if(!day()){newDayWizard();return false;}if(day().reviewed){toast('This day has been followed up and is read-only. Start a new day to continue.');return false;}return true;}
function openModal(title,content,wide=false){if(!modalRoot.querySelector('dialog'))modalReturnFocus=document.activeElement;modalRoot.innerHTML=`<dialog class="modal ${wide?'wide':''}" aria-labelledby="modal-title"><div class="modal-heading"><h2 id="modal-title">${title}</h2><button class="icon-btn" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button></div>${content}</dialog>`;const dialog=modalRoot.querySelector('dialog');dialog.showModal();dialog.addEventListener('close',()=>{if(modalRoot.firstElementChild!==dialog)return;modalRoot.innerHTML='';modalReturnFocus?.focus?.();});}
function closeModal(){modalRoot.querySelector('dialog')?.close();}
const errorBox=()=>'<p class="form-error" role="alert"></p>';
function formError(text){const el=modalRoot.querySelector('.form-error')||app.querySelector('.form-error');if(el){el.textContent=text;el.scrollIntoView({block:'nearest'});}else toast(text);}
function deptOptions(value='',all=true){return `${all?'<option value="">All my departments</option>':''}${state.departments.map(d=>`<option value="${esc(d.id)}"${selected(value,d.id)}>D${esc(d.id)} · ${esc(d.name)}</option>`).join('')}`;}
function personOptions(value='',working=false){return `<option value="">Auto-assign</option>${state.team.filter(p=>p.active||p.id===value).filter(p=>!working||day()?.shifts.some(s=>s.personId===p.id)).map(p=>`<option value="${esc(p.id)}"${selected(value,p.id)}>${esc(p.name)}</option>`).join('')}`;}
function daysPicker(name,values){return `<div class="days-picker">${WEEKDAYS.map((d,i)=>`<label><input type="checkbox" name="${name}" value="${i}"${checked(values.includes(i))}><span>${d}</span></label>`).join('')}</div>`;}
function heading(title,description,actions='',eyebrow=''){return `<div class="heading-row"><div class="page-heading">${eyebrow?`<div class="eyebrow">${eyebrow}</div>`:''}<h1>${title}</h1><p>${description}</p></div><div class="heading-actions">${actions}</div></div>`;}
function datePicker(){return `<div class="date-picker"><button data-action="previous-date" aria-label="Previous planned day">‹</button><label><span class="sr-only">Plan date</span><input type="date" id="plan-date" value="${selectedDate}"></label><button data-action="next-date" aria-label="Next planned day">›</button></div>`;}
function render(){
 if(!state.profile){app.innerHTML=welcomeMarkup+(storageMessage?`<div class="recovery-banner">${esc(storageMessage)} ${btn('Restore backup','import')} ${btn('Recover last save','recover')}</div>`:'');return;}
 const titles={overview:'Overview',planner:'Daily planner',tour:'Floor tour',team:'My team',aisles:'Aisles & departments',routines:'Routines & modulars',settings:'Settings'};
 app.innerHTML=`<aside class="sidebar"><a class="brand" href="#overview"><img src="./favicon.svg" alt="">PlanIt<span>TEAM WORKSPACE</span></a><div class="nav-label">WORKSPACE</div><nav aria-label="Main navigation">${Object.entries(titles).filter(([k])=>k!=='settings').map(([key,label])=>`<button data-action="navigate" data-view="${key}" class="${view===key?'active':''}" ${view===key?'aria-current="page"':''}>${icon(key)}<span>${label}</span>${key==='planner'&&day()?`<span class="nav-count">${day().tasks.length}</span>`:''}</button>`).join('')}<button class="mobile-settings" data-action="navigate" data-view="settings">${icon('settings')}<span>Settings</span></button></nav><div class="sidebar-bottom"><div class="privacy-pill">${icon('lock',15)} On this device only</div><button data-action="navigate" data-view="settings" class="settings-nav">${icon('settings')} Settings</button><div class="account">${avatar(person(state.profile.leadId),true)}<div><b>${esc(state.profile.name)}</b><small>Team lead</small></div></div></div></aside><div class="workspace"><header class="topbar"><span>Workspace <b>/ ${titles[view]}</b></span><div class="topbar-right"><span class="local-label">${demo?'Sample workspace':loaded.unavailable?'Temporary workspace':'Saved on this device'} <span class="status-dot"></span></span>${avatar(person(state.profile.leadId),true)}</div></header>${demo?`<div class="demo-banner"><span><b>You’re exploring a sample workspace.</b> These names and results are fictional; changes stay in memory.</span>${btn('Exit sample','exit-demo')}</div>`:''}${storageMessage?`<div class="recovery-banner">${esc(storageMessage)} ${btn('Export current data','export')}</div>`:''}<main id="main" tabindex="-1">${({overview,planner,tour:tourView,team:teamView,aisles:aislesView,routines:routinesView,settings:settingsView})[view]()}</main><footer class="app-footer">PlanIt · Independent planning tool <span>Local data. Clear priorities.</span></footer></div>`;
}
function taskRow(t){const p=person(t.assignedTo);return `<button class="task-row" data-action="edit-task" data-id="${t.id}"><span class="task-status ${t.status==='done'?'done':''}">${t.status==='done'?icon('check',14):''}</span><span class="task-row-body"><b>${esc(t.title)}</b><small>${t.segments.length?clockLabel(t.segments[0].start):'Needs scheduling'} · ${duration(t.minutes)}${t.department?` · D${esc(t.department)}`:''}</small></span>${['urgent','high'].includes(t.priority)?chip(t.priority,'priority-'+t.priority):''}${p?avatar(p,true):chip('Unassigned','amber')}${icon('arrow',16)}</button>`;}
function overview(){
 const d=day(),m=dayMetrics(d),top=topstockProgress(state,selectedDate),weekly=state.days.filter(d=>d.date>=monday(selectedDate)&&d.date<=selectedDate),wm=weekly.flatMap(d=>d.tasks),zones=d?.tasks.filter(t=>t.kind==='zone')||[],needed=d?.tasks.filter(t=>t.status!=='done')||[];
 let html=heading(`Let’s make today count, ${esc(state.profile.name.split(' ')[0])}.`,formatDate(selectedDate),`${datePicker()}${btn(icon('plus')+' New day','new-day')}${btn(icon('tour')+' Conduct tour','conduct-tour','primary')}`,'YOUR TEAM. YOUR PLAN.');
 if(!d)return html+empty('A fresh day starts here','Choose who’s working, set their shifts and meals, and let your routines find their place.',btn('Set up this day '+icon('arrow'),'new-day','primary'));
 if(d.reviewed)html+=`<div class="notice">${icon('check')} Follow-up completed. This day is saved for your records. ${btn('Plan a new day','new-day')}</div>`;
 html+=`<div class="stats-grid"><article class="stat-card"><div class="stat-label">Tasks completed ${icon('check')}</div><div class="stat-value">${m.done}<span>/ ${m.total}</span></div><div class="progress-track"><span style="width:${m.percent}%"></span></div><small>${m.percent}% of the day’s tasks</small></article><article class="stat-card"><div class="stat-label">On the floor today ${icon('team')}</div><div class="stat-value">${d.shifts.length}<span>people</span></div><div class="avatar-stack">${d.shifts.map(s=>avatar(person(s.personId),true)).join('')}<small>${duration(m.capacity)} after breaks</small></div></article><article class="stat-card"><div class="stat-label">Weekly top stock ${icon('aisles')}</div><div class="stat-value">${top.done}<span>/ ${top.total} aisles</span></div><div class="progress-track blue"><span style="width:${percent(top.done,top.total)}%"></span></div><small>${top.remaining.length?`${top.remaining.length} aisles to finish by Friday`:'All eligible aisles complete'}</small></article><article class="stat-card ${m.unassigned?'attention':''}"><div class="stat-label">Needs attention ${icon('warning')}</div><div class="stat-value">${m.unassigned}<span>tasks</span></div><small>${m.unassigned?'Work that needs capacity or reassignment':'All tasks have a place in the plan'}</small>${btn('Review the plan '+icon('arrow',14),'navigate','text-link','data-view="planner"')}</article></div>`;
 html+=`<div class="dashboard-grid"><section class="card focus-card">${sectionHeader('Today’s focus',`${needed.length} tasks left to move the day forward.`,btn('View planner '+icon('arrow',15),'navigate','text-link','data-view="planner"'))}${needed.length?needed.sort((a,b)=>Number(!!a.assignedTo)-Number(!!b.assignedTo)||(a.segments[0]?.start||0)-(b.segments[0]?.start||0)).slice(0,6).map(taskRow).join(''):empty('A day well done','Everything on this plan has been completed.')}</section><section class="card week-card">${sectionHeader('A little better, every day','Task completion this week')}<div class="week-chart" role="img" aria-label="Daily task completion percentages">${Array.from({length:7},(_,i)=>{const date=addDays(monday(selectedDate),i),dm=dayMetrics(state.days.find(d=>d.date===date));return `<div class="chart-column"><span>${dm.total?dm.percent+'%':'—'}</span><div class="bar-well"><i style="height:${dm.percent}%;${date===selectedDate?'background:#1c5441':''}"></i></div><b class="${date===selectedDate?'today':''}">${WEEKDAYS[(i+1)%7]}</b></div>`;}).join('')}</div><div class="week-summary"><b>${wm.filter(t=>t.status==='done').length} tasks completed</b><span>Across ${weekly.length} planned days</span></div></section></div>`;
 const notZoned=state.aisles.filter(a=>!lastAisleWork(state,a.id,'zone',addDays(selectedDate,1))).length;
 return html+`<div class="dashboard-grid lower"><section class="card">${sectionHeader('Your team’s capacity','A balanced plan leaves room for the unexpected.')}<div class="capacity-list">${d.shifts.map(s=>{const p=person(s.personId),tasks=d.tasks.filter(t=>t.assignedTo===s.personId),scheduled=tasks.flatMap(t=>t.segments).reduce((n,t)=>n+t.end-t.start,0),cap=capacity(s);return `<button class="capacity-row" data-action="profile" data-id="${esc(s.personId)}">${avatar(p,true)}<span class="capacity-name"><b>${esc(p?.name||'Associate')}</b><small>${clockLabel(s.start)} – ${clockLabel(shiftBounds(s).end)}</small></span><span class="capacity-bar"><i style="width:${Math.min(100,percent(scheduled,cap))}%"></i></span><span class="capacity-numbers">${duration(scheduled)} / ${duration(cap)}<small>${tasks.filter(t=>t.status==='done').length} of ${tasks.length} done</small></span></button>`;}).join('')}</div></section><section class="card opportunity-card">${sectionHeader('Room to improve','Small signals for your next floor walk.')}<div class="insight"><span class="insight-symbol">01</span><div><b>${notZoned?`${notZoned} aisles without a completed zone`:'Every aisle has zoning history'}</b><p>${notZoned?'Start with the aisles you haven’t reached. Tour priorities take their place in the plan.':'Older zones are automatically prioritized next time.'}</p></div></div><div class="insight"><span class="insight-symbol">02</span><div><b>${d.tasks.filter(t=>t.source==='carry').length} tasks carried into this day</b><p>Check estimates and shift time when the same work keeps coming back.</p></div></div><div class="insight"><span class="insight-symbol">03</span><div><b>${duration(Math.max(0,m.capacity-m.scheduled))} of unallocated shift time</b><p>${zones.length} zoning assignments planned. Meals and rest breaks are reserved.</p></div></div></section></div>`;
}
function planner(){
 const d=day(),m=dayMetrics(d);let html=heading('A place for everything.',`${formatDate(selectedDate)} · ${d?duration(m.scheduled)+' scheduled · '+duration(m.capacity)+' available':'Set up a day to build the plan.'}`,`${datePicker()}${btn(icon('plus')+' Add task','add-task')}${btn(icon('spark')+' Rebalance','rebalance','primary')}`);
 if(!d)return html+empty('Your planner is ready when you are','Add shifts and meals to start assigning work.',btn('Set up day','new-day','primary'));
 const unscheduled=d.tasks.filter(t=>t.status!=='done'&&!t.segments.length);
 if(unscheduled.length)html+=`<div class="notice amber">${icon('warning')} <span><b>${unscheduled.length} tasks need scheduling.</b> Adjust shifts, assign another person, or carry them forward at follow-up.</span></div>`;
 if(d.reviewed)html+=`<div class="notice">${icon('lock')} This day is followed up and read-only.</div>`;
 html+=`<div class="planner-toolbar"><div class="segmented"><button data-action="planner-mode" data-mode="timeline" class="${plannerMode==='timeline'?'active':''}">${icon('planner',16)} Timeline</button><button data-action="planner-mode" data-mode="list" class="${plannerMode==='list'?'active':''}">List view</button></div><div class="filters"><label class="sr-only" for="person-filter">Filter by person</label><select id="person-filter"><option value="">Everyone</option>${d.shifts.map(s=>`<option value="${s.personId}"${selected(filterPerson,s.personId)}>${esc(person(s.personId)?.name)}</option>`).join('')}</select><label class="sr-only" for="status-filter">Filter by status</label><select id="status-filter"><option value="all"${selected(filterStatus,'all')}>All tasks</option><option value="pending"${selected(filterStatus,'pending')}>To do</option><option value="in-progress"${selected(filterStatus,'in-progress')}>In progress</option><option value="done"${selected(filterStatus,'done')}>Completed</option></select>${btn('Edit shifts','edit-shifts')}${btn('Follow up','follow-up')}</div></div>`;
 const filter=t=>(!filterPerson||t.assignedTo===filterPerson)&&(filterStatus==='all'||t.status===filterStatus);
 if(plannerMode==='list'){const tasks=d.tasks.filter(filter).sort((a,b)=>(a.segments[0]?.start??3000)-(b.segments[0]?.start??3000));return html+`<section class="card">${tasks.length?tasks.map(taskRow).join(''):empty('No matching tasks','Try another filter or add a task.')}</section>`;}
 const shifts=d.shifts.filter(s=>!filterPerson||s.personId===filterPerson),start=Math.floor(Math.min(...d.shifts.map(s=>s.start))/60)*60,end=Math.ceil(Math.max(...d.shifts.map(s=>shiftBounds(s).end))/60)*60,unit=2.4;
 html+=`<div class="timeline-scroller"><div class="timeline" style="--cols:${shifts.length};--timeline-height:${(end-start)*unit}px"><div class="timeline-head time-head">TIME</div>${shifts.map(s=>`<div class="timeline-head">${avatar(person(s.personId),true)}<div><b>${esc(person(s.personId)?.name)}</b><small>${clockLabel(s.start)} – ${clockLabel(shiftBounds(s).end)}</small></div><span>${d.tasks.filter(t=>t.assignedTo===s.personId).length} tasks</span></div>`).join('')}<div class="time-axis" style="height:${(end-start)*unit}px">${Array.from({length:(end-start)/60},(_,i)=>`<span style="top:${i*60*unit}px">${clockLabel(start+i*60)}</span>`).join('')}</div>${shifts.map(s=>`<div class="person-lane" data-person="${s.personId}" data-start="${start}" style="height:${(end-start)*unit}px;background-size:100% ${60*unit}px">${pauses(s).map(p=>`<div class="break-block ${p.meal?'meal':''}" style="top:${(p.start-start)*unit}px;height:${(p.end-p.start)*unit}px"><span>${p.meal?'Meal break':'Rest break'} · ${duration(p.end-p.start)}</span></div>`).join('')}${d.tasks.filter(t=>t.assignedTo===s.personId&&filter(t)).flatMap(t=>t.segments.map((seg,i)=>`<button class="schedule-task ${seg.end-seg.start<20?'compact':'full-block'} task-${t.kind} ${t.status==='done'?'completed':''}" data-action="edit-task" data-id="${t.id}" draggable="${!d.reviewed&&t.status!=='done'}" data-task="${t.id}" style="top:${(seg.start-start)*unit}px;height:${Math.max(25,(seg.end-seg.start)*unit-3)}px" title="${esc(t.title)} · ${clockLabel(seg.start)}–${clockLabel(seg.end)}${t.locked?' · Pinned':''}"><span class="task-time">${clockLabel(seg.start)} · ${duration(seg.end-seg.start)} ${t.status==='done'?'✓':t.locked?'⌑':''}</span><b>${esc(t.title)}</b>${(seg.end-seg.start)>=40?`<span>${t.source==='tour'?'Floor tour':t.source==='carry'?'Carried forward':t.kind==='zone'?'Aisle care':t.source==='routine'?'Routine':'Task'}${t.department?' · D'+esc(t.department):''}${t.segments.length>1?' · Part '+(i+1):''}</span>`:''}</button>`)).join('')}</div>`).join('')}</div></div><div class="planner-legend"><span><i class="legend-green"></i> Routine</span><span><i class="legend-blue"></i> Top stock</span><span><i class="legend-purple"></i> Zoning</span><span><i class="legend-amber"></i> Tour / custom</span><small>Click to edit. Drag to an open time to pin. Use task details on touch devices.</small></div>`;
 if(unscheduled.length)html+=`<section class="card backlog">${sectionHeader('Unscheduled work','These tasks carry forward if unfinished.')}${unscheduled.filter(filter).map(taskRow).join('')}</section>`;return html;
}
function tourView(){
 const d=day();let html=heading('See it. Note it. Plan it.','Capture priorities while you walk. Complete your tour to make room for them in the day.',btn(icon('check')+' Complete tour','complete-tour','primary'));
 if(!d||d.reviewed)return html+empty(d?'This tour is saved':'Set up your day first','The tour needs your team’s shifts to assign the work.',btn('Set up day','new-day','primary'));
 return html+`<div class="tour-layout"><section class="card tour-compose">${sectionHeader('A new observation','Add a note or prioritize an aisle for zoning.')}<form id="tour-form"><label>What needs attention?<textarea name="title" rows="3" required maxlength="300" placeholder="e.g. Refresh the cookware endcap"></textarea></label><div class="form-grid"><label>Type<select name="kind"><option value="custom">Task / observation</option><option value="zone">Zone an aisle</option></select></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><label>Department<select name="department">${deptOptions()}</select></label><label>Aisle<select name="aisleId"><option value="">No specific aisle</option>${state.aisles.map(a=>`<option value="${a.id}">${esc(a.label)} · D${esc(a.department)}</option>`).join('')}</select></label><label>Estimate (minutes)<input type="number" name="minutes" value="20" min="5" max="960" step="5" required></label><label>Assign to<select name="assignee">${personOptions('',true)}</select></label></div><label>Additional notes<textarea name="notes" rows="2" maxlength="5000" placeholder="Helpful context for whoever picks this up"></textarea></label><p class="helper">Zoning notes use your zoning window and replace that aisle’s automatic assignment. In-progress and completed work stays in place.</p>${errorBox()}<button class="btn primary full" type="submit">${icon('plus')} Add to tour</button></form></section><section class="card">${sectionHeader('On this tour',`${state.tourDraft.length} observations ready to integrate`,chip('DRAFT','gray'))}${state.tourDraft.length?state.tourDraft.map(t=>`<div class="tour-note"><div class="tour-note-top">${chip(t.priority,'priority-'+t.priority)}<button data-action="remove-note" data-id="${t.id}" class="icon-btn" aria-label="Remove note ${esc(t.title)}">${icon('close',16)}</button></div><h3>${esc(t.title)}</h3><p>${esc(t.notes)}</p><div class="note-meta">${t.kind==='zone'?'Zoning · ':''}${t.department?'D'+esc(t.department)+' · ':''}${duration(t.minutes)} · ${esc(person(t.assignee)?.name||'Auto-assign')}</div></div>`).join(''):empty('Eyes on the floor','Your observations appear here as you add them. Drafts are saved on this device.')}${d.tour.length?`<details class="tour-history"><summary>${d.tour.length} observations already integrated today</summary>${d.tour.map(t=>`<p>${esc(t.title)}</p>`).join('')}</details>`:''}</section></div>`;
}
function metricPeriod(){return metricRange==='all'?{from:'',to:selectedDate}:{from:addDays(selectedDate,-Number(metricRange)+1),to:selectedDate};}
function teamView(){
 const range=metricPeriod();let html=heading(selectedPerson?esc(person(selectedPerson)?.name||'Associate'):'Good plans start with people.','Completion, capacity, and aisle care — built from what you record.',`<label class="sr-only" for="metric-range">Metrics period</label><select id="metric-range"><option value="7"${selected(metricRange,'7')}>Last 7 days</option><option value="30"${selected(metricRange,'30')}>Last 30 days</option><option value="all"${selected(metricRange,'all')}>All history</option></select>${btn(icon('plus')+' Add associate','add-person')}`);
 html+=`<p class="metrics-context">Through ${formatDate(selectedDate,{month:'short',day:'numeric',year:'numeric'})}. Zoning completion averages recorded progress across assigned zones; carried attempts count separately.</p>`;
 if(selectedPerson){const p=person(selectedPerson),m=personMetrics(state,selectedPerson,range.from,range.to),tasks=state.days.filter(d=>d.date>=range.from&&d.date<=range.to).flatMap(d=>d.tasks.filter(t=>t.assignedTo===p.id).map(t=>({...t,date:d.date})));
 return html+`${btn('‹ Back to team','back-team','text-link')}<section class="profile-header card">${avatar(p)}<div><h2>${esc(p.name)}</h2><p>${esc(p.role)} · ${p.active?'Active':'Archived'} · ${p.departments.length?p.departments.map(id=>'D'+esc(id)).join(', '):'All your departments'}</p></div>${btn('Edit profile','edit-person','','data-id="'+p.id+'"')}</section><div class="stats-grid">${[['Task completion',m.completion===null?'—':m.completion+'%',`${m.done} of ${m.tasks} tasks`],['Average zoning completion',m.zone===null?'—':m.zone+'%',`${m.zones} assigned zones`],['Top stock completed',m.topstock,`${m.shifts} recorded shifts`],['Actual / estimated time',m.actualRatio===null?'—':m.actualRatio+'%',`${m.timed} tasks with actual time`]].map(([label,value,note])=>`<article class="stat-card"><div class="stat-label">${label}</div><div class="stat-value">${value}</div><small>${note}</small></article>`).join('')}</div><section class="card">${sectionHeader('Recent work',`${m.carry} carried attempts · ${duration(m.plannedMinutes)} estimated work`)}${tasks.length?`<div class="table-scroll"><table><thead><tr><th>Task</th><th>Day</th><th>Planned</th><th>Actual</th><th>Completion</th></tr></thead><tbody>${tasks.reverse().slice(0,100).map(t=>`<tr><td>${esc(t.title)}</td><td>${formatDate(t.date,{month:'short',day:'numeric'})}</td><td>${duration(t.minutes)}</td><td>${t.actualMinutes?duration(t.actualMinutes):'—'}</td><td>${chip(t.status==='done'?'Complete':t.progress+'%',t.status==='done'?'green':'gray')}</td></tr>`).join('')}</tbody></table></div>`:empty('No work recorded yet','Assigned tasks will build this profile over time.')}</section>`;}
 return html+`<div class="team-grid">${state.team.map(p=>{const m=personMetrics(state,p.id,range.from,range.to);return `<button class="card person-card" data-action="profile" data-id="${p.id}"><div class="person-card-top">${avatar(p)}${chip(p.active?p.role:'Archived',p.role==='Team lead'?'green':'gray')}</div><h2>${esc(p.name)}</h2><p>${m.shifts} shifts · ${m.tasks} assigned tasks</p><div class="person-stat"><span>Task completion</span><b>${m.completion===null?'—':m.completion+'%'}</b></div><div class="progress-track"><span style="width:${m.completion||0}%"></span></div><div class="person-stat"><span>Average zoning</span><b>${m.zone===null?'—':m.zone+'%'}</b></div><div class="progress-track purple"><span style="width:${m.zone||0}%"></span></div><div class="person-card-footer">View profile ${icon('arrow',17)}</div></button>`;}).join('')}</div>`;
}
function aislesView(){const top=topstockProgress(state,selectedDate);return heading('Know your floor.','Your departments, aisle coverage, and the work behind a well-kept zone.',btn('Edit workspace','edit-workspace'))+`<div class="aisle-summary"><span>${state.departments.length} departments</span><span>${state.aisles.length} aisles</span><span>${top.total} with top stock</span><span>${top.done} top-stock aisles completed this week</span></div>${state.departments.map(d=>{const aisles=state.aisles.filter(a=>a.department===d.id);return `<section class="card department-card">${sectionHeader(`<span class="department-number">${esc(d.id)}</span> ${esc(d.name)}`,`${aisles.length} aisles · ${state.settings.rfid[d.id]?.enabled?'RFID '+state.settings.rfid[d.id].days.map(n=>WEEKDAYS[n]).join(', '):'Tuesday deep outs when enabled'}`,btn(icon('plus')+' Add aisle','add-aisle','','data-department="'+esc(d.id)+'"'))}${aisles.length?`<div class="aisle-grid">${aisles.map(a=>{const last=lastAisleWork(state,a.id,'zone',addDays(selectedDate,1)),done=!top.remaining.some(x=>x.id===a.id);return `<button class="aisle-tile ${a.topstock&&done?'top-done':''}" data-action="edit-aisle" data-id="${a.id}"><div><b>${esc(a.label)}</b>${a.topstock?`<span title="Top stock">${icon('aisles',16)} ${done?'✓':''}</span>`:''}</div><p>${last?'Zoned '+formatDate(last,{month:'short',day:'numeric'}):'No completed zone yet'}</p><small>Zone ${duration(a.zoneMinutes)}${a.topstock?' · Top stock '+duration(a.topMinutes):''}</small></button>`;}).join('')}</div>`:empty('Map this department','Add aisle labels and tick the ones with top stock.')}</section>`;}).join('')}`;}
function routinesView(){return heading('Build your everyday rhythm.','Turn on the routines you use. Adjust estimates to fit your store.',btn(icon('plus')+' Repeating task','add-repeat','primary'))+`<div class="notice">${icon('clock')} <span>Editable planning defaults, not verified company time standards. Changes apply to new days; refresh pending routines below to use them today.</span>${btn('Apply to current day','apply-routines')}</div><section class="card">${sectionHeader('Routine library','The recurring work that keeps your departments moving.')}<div class="routine-grid">${ROUTINES.map(r=>{const cfg=state.settings.routines[r.id];return `<div class="routine-item"><div class="routine-icon">${icon(['zone','topstock'].includes(r.id)?'aisles':'routines')}</div><div class="routine-description"><b>${r.name}</b><p>${r.description}</p><button class="text-link" data-action="configure-routine" data-id="${r.id}">${['topstock','zone'].includes(r.id)?'Aisle estimates':duration(cfg.minutes)} · Configure ${icon('arrow',13)}</button></div><label class="switch"><input type="checkbox" data-routine-toggle="${r.id}"${checked(cfg.enabled)} aria-label="Enable ${r.name}"><span></span></label></div>`;}).join('')}</div></section><section class="card section-gap">${sectionHeader('Repeating tasks','Your own routines, on the days you choose.',btn('Add task','add-repeat'))}${state.repeats.length?state.repeats.map(r=>`<div class="library-row"><div><b>${esc(r.title)}</b><small>${r.days.map(d=>WEEKDAYS[d]).join(', ')} · ${duration(r.minutes)} · ${r.active?'Active':'Paused'}</small></div>${btn('Edit','edit-repeat','','data-id="'+r.id+'"')}</div>`).join(''):empty('Make room for your routines','Add weekly checks, recurring projects, or other work your team owns.')}</section><section class="card section-gap">${sectionHeader('Modular categories','Due or undated categories join new plans when Modulars is enabled.',btn(icon('plus')+' Add modular','add-modular'))}${state.modulars.length?`<div class="table-scroll"><table><thead><tr><th>Category</th><th>Department</th><th>Sections</th><th>Estimate</th><th>Due / status</th><th></th></tr></thead><tbody>${state.modulars.map(m=>`<tr><td><b>${esc(m.category)}</b><small>${esc(m.description)}</small></td><td>D${esc(m.department)}</td><td>${m.sections}</td><td>${duration(m.minutes)}</td><td>${m.completed?chip('Complete','green'):esc(m.dueDate||'Next plan')}</td><td>${btn('Edit','edit-modular','','data-id="'+m.id+'"')}</td></tr>`).join('')}</tbody></table></div>`:empty('A home for your next reset','Track the department, category number, sections, and completion estimate.')}</section>`;}
function settingsView(){return heading('Your workspace, your way.','Manage your setup and the information saved on this device.')+`<div class="settings-layout"><section class="card">${sectionHeader('Workspace')}<div class="library-row"><div><b>Floor map & aisle history</b><small>See zoning recency and weekly top-stock coverage.</small></div>${btn('View aisles','navigate','','data-view="aisles"')}</div><div class="library-row"><div><b>${esc(state.profile.name)}’s workspace</b><small>${state.departments.length} departments · ${state.aisles.length} aisles · ${state.team.filter(p=>p.active).length} active people</small></div>${btn('Edit setup','edit-workspace')}</div><div class="library-row"><div><b>Planning defaults</b><small>Routine estimates, scan days, reshop windows, and zoning.</small></div>${btn('Manage routines','navigate','','data-view="routines"')}</div><div class="library-row"><div><b>Sample workspace</b><small>Try the planner with fictional data, separate from your saved work.</small></div>${btn('Explore sample','demo')}</div></section><section class="card">${sectionHeader('Local data & backups','Names, shifts, notes, and metrics are stored in this browser on this device.')}<p>PlanIt has no account, analytics, cloud database, or Walmart system connection. Clearing site data or changing browsers removes access to this workspace. Anyone with access to this browser profile may be able to view it.</p><p class="helper">A downloaded backup contains your personal planning data. Keep it somewhere private. GitHub receives normal page requests, but the app never sends your workspace data to GitHub or other services.</p><div class="button-row">${btn(icon('download')+' Export backup','export','primary')}${btn('Restore backup','import')}${btn('Recover last save','recover')}</div><div class="divider"></div>${btn('Erase this workspace','reset','danger')}</section></div><section class="card section-gap">${sectionHeader('Public references & planning assumptions','References checked September 13, 2026. Department names can be customized for your store.')}<p class="helper">Tuesday deep outs, Friday top-stock coverage, daily Pinpoint, and other routine timings are the requested planning rules, not verified universal Walmart policy. Check your current store guidance. You enter meal and rest-break times; PlanIt does not enforce employment rules.</p><div class="reference-grid">${SOURCES.map(s=>`<a class="reference" href="${s.url}" target="_blank" rel="noopener noreferrer"><b>${s.title} ↗</b><small>${s.publisher}</small><p>${s.note}</p></a>`).join('')}</div><p class="helper">PlanIt is independently made and is not affiliated with or endorsed by Walmart.</p></section>`;}
